// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file did/v1/query.proto (package did.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsResponse, QueryRequest, QueryResolveResponse, QueryVerifyRequest, QueryVerifyResponse } from "./query_pb.js";

const TYPE_NAME = "did.v1.Query";

/**
 * Params queries all parameters of the module.
 *
 * @generated from rpc did.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * Resolve queries the DID document by its id.
 *
 * @generated from rpc did.v1.Query.Resolve
 */
export const QueryResolveService = {
  typeName: TYPE_NAME,
  method: "Resolve",
  Request: QueryRequest,
  Response: QueryResolveResponse,
} as const;

/**
 * Verify verifies a message with the DID document
 *
 * @generated from rpc did.v1.Query.Verify
 */
export const QueryVerifyService = {
  typeName: TYPE_NAME,
  method: "Verify",
  Request: QueryVerifyRequest,
  Response: QueryVerifyResponse,
} as const;

