// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package model

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            string       `json:"id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	Number        int64        `json:"number"`
	Sequence      int64        `json:"sequence"`
	Address       string       `json:"address"`
	PublicKey     string       `json:"public_key"`
	ChainID       string       `json:"chain_id"`
	Controller    string       `json:"controller"`
	IsSubsidiary  bool         `json:"is_subsidiary"`
	IsValidator   bool         `json:"is_validator"`
	IsDelegator   bool         `json:"is_delegator"`
	IsAccountable bool         `json:"is_accountable"`
}

type Credential struct {
	ID                      string       `json:"id"`
	CreatedAt               time.Time    `json:"created_at"`
	UpdatedAt               time.Time    `json:"updated_at"`
	DeletedAt               sql.NullTime `json:"deleted_at"`
	Handle                  string       `json:"handle"`
	CredentialID            string       `json:"credential_id"`
	AuthenticatorAttachment string       `json:"authenticator_attachment"`
	Origin                  string       `json:"origin"`
	Type                    string       `json:"type"`
	Transports              string       `json:"transports"`
}

type Device struct {
	ID             string         `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	ProfileID      string         `json:"profile_id"`
	CredentialID   string         `json:"credential_id"`
	Name           string         `json:"name"`
	DeviceType     string         `json:"device_type"`
	OsName         string         `json:"os_name"`
	OsVersion      string         `json:"os_version"`
	BrowserName    sql.NullString `json:"browser_name"`
	BrowserVersion sql.NullString `json:"browser_version"`
	LastUsedAt     time.Time      `json:"last_used_at"`
	IsTrusted      bool           `json:"is_trusted"`
	IsCurrent      bool           `json:"is_current"`
	Fingerprint    string         `json:"fingerprint"`
	UserAgent      sql.NullString `json:"user_agent"`
	IpAddress      sql.NullString `json:"ip_address"`
}
