# Top-level configuration
name = "motr-vault"
main = "./worker.mjs"
compatibility_date = "2025-04-14"

[build]
command = "bun run build"

[dev]
port = 8788

[observability]
enabled = true

[[d1_databases]]
binding = "COMMON_DB" # available in your Worker on env.DB
database_name = "motr-common-db"
database_id = "701488b4-de41-4f75-9ca9-b4d37acf621e"

[[d1_databases]]
binding = "CONTROLLER_DB" # available in your Worker on env.DB
database_name = "motr-controller-db"
database_id = "872a4b08-7e07-4978-b227-5b60940238ed"

[vars]
SONR_CHAIN_ID = 'sonr-testnet-1'
IPFS_GATEWAY = 'https://ipfs.sonr.land'
SONR_API_URL = 'https://api.sonr.land'
SONR_RPC_URL = 'https://rpc.sonr.land'
SONR_GRPC_URL = 'https://grpc.sonr.land'
MATRIX_SERVER = 'https://bm.chat'
MOTR_MODE = 'controller'


