// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package activity

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetActivityByID(ctx context.Context, id string) (Activity, error)
	GetActivityByTxHash(ctx context.Context, txHash sql.NullString) (Activity, error)
	GetHealthByEndpoint(ctx context.Context, endpointUrl string) (Health, error)
	GetHealthByID(ctx context.Context, id string) (Health, error)
	GetServiceByAddress(ctx context.Context, address string) (Service, error)
	GetServiceByChainAndAddress(ctx context.Context, arg GetServiceByChainAndAddressParams) (Service, error)
	GetServiceByID(ctx context.Context, id string) (Service, error)
	// ACTIVITY QUERIES
	InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error)
	// HEALTH QUERIES
	InsertHealth(ctx context.Context, arg InsertHealthParams) (Health, error)
	InsertService(ctx context.Context, arg InsertServiceParams) (Service, error)
	ListActivitiesByAccount(ctx context.Context, arg ListActivitiesByAccountParams) ([]Activity, error)
	ListActivitiesByStatus(ctx context.Context, arg ListActivitiesByStatusParams) ([]Activity, error)
	ListActivitiesByType(ctx context.Context, arg ListActivitiesByTypeParams) ([]Activity, error)
	ListHealthByChain(ctx context.Context, arg ListHealthByChainParams) ([]Health, error)
	ListHealthByStatus(ctx context.Context, arg ListHealthByStatusParams) ([]Health, error)
	ListHealthChecksNeedingUpdate(ctx context.Context, limit int64) ([]Health, error)
	ListServicesByChain(ctx context.Context, arg ListServicesByChainParams) ([]Service, error)
	ListServicesByOwner(ctx context.Context, arg ListServicesByOwnerParams) ([]Service, error)
	SoftDeleteActivity(ctx context.Context, id string) error
	SoftDeleteHealth(ctx context.Context, id string) error
	SoftDeleteService(ctx context.Context, id string) error
	UpdateActivityStatus(ctx context.Context, arg UpdateActivityStatusParams) (Activity, error)
	UpdateHealthCheck(ctx context.Context, arg UpdateHealthCheckParams) (Health, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
