# Bun 1.3.0 Configuration for Motr Monorepo
# https://bun.com/docs/runtime/bunfig

# Global log level - "debug" | "warn" | "error"
logLevel = "warn"

[install]
# Link workspace packages together for monorepo
linkWorkspacePackages = true

# Auto-install peer dependencies
peer = true

# Use exact versions for better reproducibility in production
exact = false

# Hoisted linker for maximum performance and smaller node_modules
linker = "hoisted"

# Production optimization: dedupe packages
dedupe = true

# Frozen lockfile in CI (uncomment for CI environments)
# frozenLockfile = true

# Concurrent downloads for faster installs
concurrent = 100

[install.cache]
# Cache directory for faster subsequent installs
dir = "~/.cache/bun/install"

# Enable cache for performance
disable = false

# Use cached manifests when available
disableManifest = false

[install.scopes]
# Optimize package resolution for common scopes
"@sonr.io" = { workspace = true }
"@radix-ui" = { registry = "https://registry.npmjs.org/" }
"@tanstack" = { registry = "https://registry.npmjs.org/" }
"@cloudflare" = { registry = "https://registry.npmjs.org/" }
"@biomejs" = { registry = "https://registry.npmjs.org/" }

[test]
# Use happy-dom for faster DOM testing
preload = ["happy-dom"]
coverage = true
# Run tests in parallel for speed
smol = false

[run]
# Use Bun's native shell for faster script execution
shell = "bun"

# Show script output
silent = false

# Bun-native script features
bun = true
