# Bun 1.3.0 Configuration for Motr Monorepo
# https://bun.com/docs/runtime/bunfig

# Global log level - "debug" | "warn" | "error"
logLevel = "warn"

[install]
# Link workspace packages together
linkWorkspacePackages = true

# Auto-install peer dependencies
peer = true

# Use exact versions for better reproducibility
exact = false

# Hoisted linker for better performance
linker = "hoisted"

# Frozen lockfile in CI
# frozenLockfile = true  # Uncomment in CI

[install.cache]
# Cache directory
dir = "~/.cache/bun/install"

# Don't disable cache
disable = false

# Don't always fetch latest (use cache when available)
disableManifest = false

[install.scopes]
# Optimize package resolution for common scopes
"@sonr.io" = { workspace = true }
"@radix-ui" = { registry = "https://registry.npmjs.org/" }
"@tanstack" = { registry = "https://registry.npmjs.org/" }

[test]
# Use happy-dom for faster tests
preload = ["happy-dom"]
coverage = true

[run]
# Enable bun shell for scripts (faster than sh)
shell = "bun"

# Don't silence output
silent = false
