version: "3.8"

services:
  resolver:
    build:
      context: ./resolver
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=development
    volumes:
      - ./resolver:/work
    restart: unless-stopped

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    ports:
      - "8788:8787"
    environment:
      - NODE_ENV=development
    volumes:
      - ./controller:/work
    restart: unless-stopped
