 packages:
   # CLI tools
   - "cli/*"
   # Core packages
   - "packages/*"
   # Template packages
   - "templates/*"
   # Web applications
   - "web/*"
   # Applications
   - "apps/*"
   # Command packages (e.g., enclave)
   - "cmd/*"
   # Example applications
   - "examples/*"
   # Documentation (if needed in future)
   # - "docs"
