# yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
silent: true

# vars:
#   VERSION:
#     sh: git describe --tags
#   COMMIT:
#     sh: git log -1 --format='%H'
#

tasks:
  default:
    cmds:
      - task: gen:templ
      - task: gen:sqlc
      - task: build

  gen:templ:
    desc: Generate code
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"
    cmds:
      - templ generate

  gen:sqlc:
    desc: Generate code
    sources:
      - x/**/model/*.sql
    generates:
      - x/**/model/*.go
    cmds:
      - sqlc generate -f "x/identity/model/sqlc.yaml"
      - sqlc generate -f "x/portfolio/model/sqlc.yaml"
      - sqlc generate -f "x/user/model/sqlc.yaml"

  build:
    desc: Build
    watch: true
    sources:
      - "**/*.go"
    generates:
      - web/app.wasm
    deps:
      - task: gen:templ
      - task: gen:sqlc
    vars:
      TIME:
        sh: date
    cmds:
      - rm -rf web/vault.wasm
      - GOOS=js GOARCH=wasm go build -o web/vault.wasm .
      - gum log --time rfc822 --level info "[BUILD] WASM Complete"

  serve:
    desc: Serve
    dir: web
    cmds:
      - bunx live-server

  test:
    desc: Test
    cmds:
      - go test -v ./...
