#yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
silent: true
vars:
  ROOT_DIR:
    sh: git rev-parse --show-toplevel

tasks:
  clean:
    desc: Remove build artifacts
    cmds:
      - task: tidy:vault
      - task: tidy:front
      - go mod tidy
      - rm -rf .task

  deploy:
    desc: Deploy all
    cmds:
      - task: deploy:vault
      - task: deploy:front

  build:
    desc: Build all
    cmds:
      - task: build:vault
      - task: build:front

  start:vault:
    desc: Start the vault
    dir: "{{.ROOT_DIR}}/cmd/vault"
    cmd: bun run start

  start:front:
    desc: Start the frontend
    dir: "{{.ROOT_DIR}}/cmd/front"
    cmd: bun run start

  build:vault:
    desc: Build the vault
    dir: "{{.ROOT_DIR}}/cmd/vault"
    cmd: bun run build
    sources:
      - main.go
    generates:
      - build/app.wasm

  build:front:
    desc: Build the frontend
    dir: "{{.ROOT_DIR}}/cmd/front"
    cmd: bun run build
    sources:
      - main.go
    generates:
      - build/app.wasm

  deploy:vault:
    desc: Deploy the vault
    dir: "{{.ROOT_DIR}}/cmd/vault"
    cmds:
      - bun run deploy

  deploy:front:
    desc: Deploy the frontend
    dir: "{{.ROOT_DIR}}/cmd/front"
    cmd: bun run deploy

  gen:templ:
    desc: Generate templ
    cmd: templ generate

  gen:sqlc:
    desc: Generate sqlc
    cmd: sqlc generate

  db:migrate:
    desc: Migrate the database
    prompt:
      - Are you sure you want to run this command? This will delete all data in the database.
    cmds:
      - task: migrate:d1
      - task: gen:sqlc

  migrate:d1:
    internal: true
    desc: Migrate the common database
    dir: "{{.ROOT_DIR}}/cmd/vault"
    cmd: npm run migrate
    sources:
      - schema.sql
    generates:
      - schema.sql


  tidy:vault:
    desc: Go mod tidy the vault
    internal: true
    dir: "{{.ROOT_DIR}}/cmd/vault"
    cmds:
      - bun run clean
      - rm -rf ./build
      - rm -rf ./dist

  tidy:front:
    desc: Go mod tidy the frontend
    internal: true
    dir: "{{.ROOT_DIR}}/cmd/front"
    cmds:
      - bun run clean
      - rm -rf ./build
      - rm -rf ./dist
