#:schema node_modules/wrangler/config-schema.json
name = "sonr-id"
main = "src/worker.ts"
compatibility_date = "2025-01-11"
compatibility_flags = ["nodejs_compat"]

# Assets configuration for serving static files
[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

# Production environment
[env.production]
name = "sonr-id"
workers_dev = false
routes = [
  { pattern = "sonr.id/*", custom_domain = true },
  { pattern = "*.sonr.id/*", custom_domain = true },
]

[env.production.vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "sonr-id-staging"
workers_dev = true

[env.staging.vars]
ENVIRONMENT = "staging"

# Development configuration
[dev]
port = 6165
local_protocol = "http"
ip = "0.0.0.0"

# Build configuration
[build]
command = "bunx --bun vite build && tsc"
cwd = "."

# Durable Objects from @pkgs/cloudflare
[[durable_objects.bindings]]
name = "COUNTER"
class_name = "CounterDurable"

[[durable_objects.bindings]]
name = "SONR_IDENTITY"
class_name = "SonrIdentityDurable"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_classes = ["CounterDurable"]

[[migrations]]
tag = "v2"
new_classes = ["SonrIdentityDurable"]

# Workflows from @pkgs/cloudflare
[[workflows]]
binding = "OTP_EMAIL_WORKFLOW"
name = "otp-email-workflow"
class_name = "OTPEmailWorkflow"

# KV namespace for OTP storage
[[kv_namespaces]]
binding = "OTP_STORE"
id = "otp-store-dev"

# Environment variables for email sending
[vars]
EMAIL_FROM = "Sonr Identity <noreply@sonr.id>"

# Observability
[observability]
enabled = true
head_sampling_rate = 1.0
