# Top-level configuration
name = "motr-front"
main = "build/worker.mjs"
compatibility_date = "2025-04-14"

routes = [
  { pattern = "sonr.id", custom_domain = true },
]

[build]
command = "npm run build"

[dev]
port = 8787

[observability]
enabled = true
logpush = true

[[d1_databases]]
binding = "COMMON_DB" # available in your Worker on env.DB
database_name = "motr-common-db"
database_id = "701488b4-de41-4f75-9ca9-b4d37acf621e"

[vars]
SONR_CHAIN_ID = 'sonr-testnet-1'
IPFS_GATEWAY = 'https://ipfs.sonr.land'
SONR_API_URL = 'https://api.sonr.land'
SONR_RPC_URL = 'https://rpc.sonr.land'
SONR_GRPC_URL = 'https://grpc.sonr.id'
MATRIX_SERVER = 'https://bm.chat'
MOTR_GATEWAY = 'https://sonr.id'
MOTR_VAULT = 'https://did.run'
MOTR_MODE = 'resolver'
