# yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
tasks:
  default:
    cmds:
      - task: gen:templ

  gen:
    aliases:
      - gen
      - g
    cmds:
      - templ generate
      - gum log --level info --time kitchen "[UI] Templ files generated"
