// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file babylon/checkpointing/v1/tx.proto (package babylon.checkpointing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgWrappedCreateValidator, MsgWrappedCreateValidatorResponse } from "./tx_pb.js";

const TYPE_NAME = "babylon.checkpointing.v1.Msg";

/**
 * WrappedCreateValidator defines a method for registering a new validator
 *
 * @generated from rpc babylon.checkpointing.v1.Msg.WrappedCreateValidator
 */
export const MsgWrappedCreateValidatorService = {
  typeName: TYPE_NAME,
  method: "WrappedCreateValidator",
  Request: MsgWrappedCreateValidator,
  Response: MsgWrappedCreateValidatorResponse,
} as const;

