// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file babylon/monitor/v1/query.proto (package babylon.monitor.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryEndedEpochBtcHeightRequest, QueryEndedEpochBtcHeightResponse, QueryReportedCheckpointBtcHeightRequest, QueryReportedCheckpointBtcHeightResponse } from "./query_pb.js";

const TYPE_NAME = "babylon.monitor.v1.Query";

/**
 * EndedEpochBtcHeight returns the BTC light client height at provided epoch
 * finish
 *
 * @generated from rpc babylon.monitor.v1.Query.EndedEpochBtcHeight
 */
export const QueryEndedEpochBtcHeightService = {
  typeName: TYPE_NAME,
  method: "EndedEpochBtcHeight",
  Request: QueryEndedEpochBtcHeightRequest,
  Response: QueryEndedEpochBtcHeightResponse,
} as const;

/**
 * ReportedCheckpointBtcHeight returns the BTC light client height at which
 * the checkpoint with the given hash is reported back to Babylon
 *
 * @generated from rpc babylon.monitor.v1.Query.ReportedCheckpointBtcHeight
 */
export const QueryReportedCheckpointBtcHeightService = {
  typeName: TYPE_NAME,
  method: "ReportedCheckpointBtcHeight",
  Request: QueryReportedCheckpointBtcHeightRequest,
  Response: QueryReportedCheckpointBtcHeightResponse,
} as const;

