// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package account

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            string       `json:"id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	Number        int64        `json:"number"`
	Sequence      int64        `json:"sequence"`
	Address       string       `json:"address"`
	PublicKey     string       `json:"public_key"`
	ChainID       string       `json:"chain_id"`
	Controller    string       `json:"controller"`
	IsSubsidiary  bool         `json:"is_subsidiary"`
	IsValidator   bool         `json:"is_validator"`
	IsDelegator   bool         `json:"is_delegator"`
	IsAccountable bool         `json:"is_accountable"`
}
