// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package account

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	GetAccountByAddress(ctx context.Context, address string) (Account, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetAccountsByChainID(ctx context.Context, chainID string) ([]Account, error)
	GetAccountsByController(ctx context.Context, controller string) ([]Account, error)
	GetDelegatorAccounts(ctx context.Context) ([]Account, error)
	GetValidatorAccounts(ctx context.Context) ([]Account, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	SoftDeleteAccount(ctx context.Context, id string) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountSequence(ctx context.Context, arg UpdateAccountSequenceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
