#:schema node_modules/wrangler/config-schema.json
name = "motr-orchestrator"
main = "src/worker.ts"
compatibility_date = "2025-01-11"
compatibility_flags = ["nodejs_compat"]

# Assets configuration - Wrangler will bundle these into the worker
# The public directory structure (in monorepo root):
# public/
#   auth/ (apps/auth/dist)
#   console/ (apps/console/dist)
#   profile/ (apps/profile/dist)
#   search/ (apps/search/dist)
#   wasm/ (WASM binaries)
[assets]
directory = "../../public"

# Production environment
[env.production]
name = "motr-orchestrator"
workers_dev = false
routes = [
  { pattern = "sonr.id/*", custom_domain = true },
  { pattern = "*.sonr.id/*", custom_domain = true },
  { pattern = "console.sonr.id/*", custom_domain = true },
  { pattern = "profile.sonr.id/*", custom_domain = true },
  { pattern = "search.sonr.id/*", custom_domain = true },
]

[env.production.vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "motr-orchestrator-staging"
workers_dev = true

[env.staging.vars]
ENVIRONMENT = "staging"

# Development configuration
[dev]
port = 5165
local_protocol = "http"
ip = "0.0.0.0"

# Service binding to the Enclave Worker
# The Enclave Worker hosts the SonrIdentityDurable Durable Object
[[services]]
binding = "ENCLAVE"
service = "motr-enclave"

# KV namespace for session management
[[kv_namespaces]]
binding = "SESSIONS"
id = "TBD_SESSIONS_ID"
preview_id = "TBD_SESSIONS_PREVIEW_ID"

# KV namespace for OTP storage (shared)
[[kv_namespaces]]
binding = "OTP_STORE"
id = "0943b06e4f5b46799d4c16b794d62279"
preview_id = "cf5b397898a34b01a62fd92aa82f18a6"

# KV namespace for Chain Registry (shared)
[[kv_namespaces]]
binding = "CHAIN_REGISTRY"
id = "6cd19a6b02294ad6b6b3e8d1341ccfa2"
preview_id = "360aa630a9184acf8e1e70d77c230849"

# KV namespace for Asset Registry (shared)
[[kv_namespaces]]
binding = "ASSET_REGISTRY"
id = "cd3daa64727b409c81c41472cd688ab2"
preview_id = "cd3daa64727b409c81c41472cd688ab2"

# Environment variables
[vars]
EMAIL_FROM = "Sonr Identity <noreply@sonr.id>"

# Observability
[observability]
enabled = true
head_sampling_rate = 1.0
