// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package model

import (
	"database/sql"
	"time"
)

type Profile struct {
	ID        string       `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Address   string       `json:"address"`
	Handle    string       `json:"handle"`
	Origin    string       `json:"origin"`
	Name      string       `json:"name"`
}

type Session struct {
	ID             string       `json:"id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	BrowserName    string       `json:"browser_name"`
	BrowserVersion string       `json:"browser_version"`
	ClientIpaddr   string       `json:"client_ipaddr"`
	Platform       string       `json:"platform"`
	IsDesktop      bool         `json:"is_desktop"`
	IsMobile       bool         `json:"is_mobile"`
	IsTablet       bool         `json:"is_tablet"`
	IsTv           bool         `json:"is_tv"`
	IsBot          bool         `json:"is_bot"`
	Challenge      string       `json:"challenge"`
	IsHumanFirst   bool         `json:"is_human_first"`
	IsHumanLast    bool         `json:"is_human_last"`
	ProfileID      int64        `json:"profile_id"`
}

type Vault struct {
	ID          string       `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Handle      string       `json:"handle"`
	Origin      string       `json:"origin"`
	Address     string       `json:"address"`
	Cid         string       `json:"cid"`
	Config      string       `json:"config"`
	SessionID   string       `json:"session_id"`
	RedirectUri string       `json:"redirect_uri"`
}
