VERSION 0.8

docker:
    FROM oven/bun:1.2.0
    WORKDIR /work
    COPY package.json .
    RUN bun install
    COPY . .
    EXPOSE 8787
    CMD ["bun", "run", "start"]
    SAVE IMAGE motr-resolver:latest
