// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package model

import (
	"context"
	"database/sql"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    id,
    name,
    symbol,
    decimals,
    chain_id,
    channel,
    asset_type,
    coingecko_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id
`

type CreateAssetParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Symbol      string         `json:"symbol"`
	Decimals    int64          `json:"decimals"`
	ChainID     string         `json:"chain_id"`
	Channel     string         `json:"channel"`
	AssetType   string         `json:"asset_type"`
	CoingeckoID sql.NullString `json:"coingecko_id"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.ID,
		arg.Name,
		arg.Symbol,
		arg.Decimals,
		arg.ChainID,
		arg.Channel,
		arg.AssetType,
		arg.CoingeckoID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ChainID,
		&i.Channel,
		&i.AssetType,
		&i.CoingeckoID,
	)
	return i, err
}

const createBalance = `-- name: CreateBalance :one
INSERT INTO balances (
    id,
    account_id,
    asset_id,
    amount,
    last_updated_height,
    is_delegated,
    is_staked,
    is_vesting
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, deleted_at, account_id, asset_id, amount, last_updated_height, is_delegated, is_staked, is_vesting
`

type CreateBalanceParams struct {
	ID                string `json:"id"`
	AccountID         string `json:"account_id"`
	AssetID           string `json:"asset_id"`
	Amount            string `json:"amount"`
	LastUpdatedHeight int64  `json:"last_updated_height"`
	IsDelegated       bool   `json:"is_delegated"`
	IsStaked          bool   `json:"is_staked"`
	IsVesting         bool   `json:"is_vesting"`
}

// Balance table methods
func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, createBalance,
		arg.ID,
		arg.AccountID,
		arg.AssetID,
		arg.Amount,
		arg.LastUpdatedHeight,
		arg.IsDelegated,
		arg.IsStaked,
		arg.IsVesting,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.AssetID,
		&i.Amount,
		&i.LastUpdatedHeight,
		&i.IsDelegated,
		&i.IsStaked,
		&i.IsVesting,
	)
	return i, err
}

const createChain = `-- name: CreateChain :one
INSERT INTO chains (
    id,
    chain_id,
    chain_name,
    pretty_name,
    network_type,
    bech32_prefix,
    daemon_name,
    node_home,
    slip44,
    fees,
    staking_denom,
    logo_uri,
    apis,
    explorers,
    is_enabled,
    status,
    codebase
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase
`

type CreateChainParams struct {
	ID           string         `json:"id"`
	ChainID      string         `json:"chain_id"`
	ChainName    string         `json:"chain_name"`
	PrettyName   string         `json:"pretty_name"`
	NetworkType  string         `json:"network_type"`
	Bech32Prefix string         `json:"bech32_prefix"`
	DaemonName   string         `json:"daemon_name"`
	NodeHome     string         `json:"node_home"`
	Slip44       int64          `json:"slip44"`
	Fees         string         `json:"fees"`
	StakingDenom string         `json:"staking_denom"`
	LogoUri      sql.NullString `json:"logo_uri"`
	Apis         string         `json:"apis"`
	Explorers    sql.NullString `json:"explorers"`
	IsEnabled    bool           `json:"is_enabled"`
	Status       string         `json:"status"`
	Codebase     sql.NullString `json:"codebase"`
}

// Chain table methods
func (q *Queries) CreateChain(ctx context.Context, arg CreateChainParams) (Chain, error) {
	row := q.db.QueryRowContext(ctx, createChain,
		arg.ID,
		arg.ChainID,
		arg.ChainName,
		arg.PrettyName,
		arg.NetworkType,
		arg.Bech32Prefix,
		arg.DaemonName,
		arg.NodeHome,
		arg.Slip44,
		arg.Fees,
		arg.StakingDenom,
		arg.LogoUri,
		arg.Apis,
		arg.Explorers,
		arg.IsEnabled,
		arg.Status,
		arg.Codebase,
	)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChainID,
		&i.ChainName,
		&i.PrettyName,
		&i.NetworkType,
		&i.Bech32Prefix,
		&i.DaemonName,
		&i.NodeHome,
		&i.Slip44,
		&i.Fees,
		&i.StakingDenom,
		&i.LogoUri,
		&i.Apis,
		&i.Explorers,
		&i.IsEnabled,
		&i.Status,
		&i.Codebase,
	)
	return i, err
}

const getAssetByCoingeckoID = `-- name: GetAssetByCoingeckoID :one
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE coingecko_id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAssetByCoingeckoID(ctx context.Context, coingeckoID sql.NullString) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByCoingeckoID, coingeckoID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ChainID,
		&i.Channel,
		&i.AssetType,
		&i.CoingeckoID,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAssetByID(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ChainID,
		&i.Channel,
		&i.AssetType,
		&i.CoingeckoID,
	)
	return i, err
}

const getAssetBySymbolAndChain = `-- name: GetAssetBySymbolAndChain :one
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE symbol = ? AND chain_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetAssetBySymbolAndChainParams struct {
	Symbol  string `json:"symbol"`
	ChainID string `json:"chain_id"`
}

func (q *Queries) GetAssetBySymbolAndChain(ctx context.Context, arg GetAssetBySymbolAndChainParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetBySymbolAndChain, arg.Symbol, arg.ChainID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ChainID,
		&i.Channel,
		&i.AssetType,
		&i.CoingeckoID,
	)
	return i, err
}

const getBalanceByAccountAndAsset = `-- name: GetBalanceByAccountAndAsset :one
SELECT id, created_at, updated_at, deleted_at, account_id, asset_id, amount, last_updated_height, is_delegated, is_staked, is_vesting FROM balances
WHERE account_id = ? AND asset_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetBalanceByAccountAndAssetParams struct {
	AccountID string `json:"account_id"`
	AssetID   string `json:"asset_id"`
}

func (q *Queries) GetBalanceByAccountAndAsset(ctx context.Context, arg GetBalanceByAccountAndAssetParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalanceByAccountAndAsset, arg.AccountID, arg.AssetID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.AssetID,
		&i.Amount,
		&i.LastUpdatedHeight,
		&i.IsDelegated,
		&i.IsStaked,
		&i.IsVesting,
	)
	return i, err
}

const getBalanceByID = `-- name: GetBalanceByID :one
SELECT id, created_at, updated_at, deleted_at, account_id, asset_id, amount, last_updated_height, is_delegated, is_staked, is_vesting FROM balances
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetBalanceByID(ctx context.Context, id string) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalanceByID, id)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.AssetID,
		&i.Amount,
		&i.LastUpdatedHeight,
		&i.IsDelegated,
		&i.IsStaked,
		&i.IsVesting,
	)
	return i, err
}

const getChainByChainID = `-- name: GetChainByChainID :one
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE chain_id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetChainByChainID(ctx context.Context, chainID string) (Chain, error) {
	row := q.db.QueryRowContext(ctx, getChainByChainID, chainID)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChainID,
		&i.ChainName,
		&i.PrettyName,
		&i.NetworkType,
		&i.Bech32Prefix,
		&i.DaemonName,
		&i.NodeHome,
		&i.Slip44,
		&i.Fees,
		&i.StakingDenom,
		&i.LogoUri,
		&i.Apis,
		&i.Explorers,
		&i.IsEnabled,
		&i.Status,
		&i.Codebase,
	)
	return i, err
}

const getChainByID = `-- name: GetChainByID :one
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetChainByID(ctx context.Context, id string) (Chain, error) {
	row := q.db.QueryRowContext(ctx, getChainByID, id)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChainID,
		&i.ChainName,
		&i.PrettyName,
		&i.NetworkType,
		&i.Bech32Prefix,
		&i.DaemonName,
		&i.NodeHome,
		&i.Slip44,
		&i.Fees,
		&i.StakingDenom,
		&i.LogoUri,
		&i.Apis,
		&i.Explorers,
		&i.IsEnabled,
		&i.Status,
		&i.Codebase,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE deleted_at IS NULL
ORDER BY chain_id, symbol
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ChainID,
			&i.Channel,
			&i.AssetType,
			&i.CoingeckoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByChain = `-- name: ListAssetsByChain :many
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE chain_id = ? AND deleted_at IS NULL
ORDER BY symbol
`

func (q *Queries) ListAssetsByChain(ctx context.Context, chainID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByChain, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ChainID,
			&i.Channel,
			&i.AssetType,
			&i.CoingeckoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByType = `-- name: ListAssetsByType :many
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE asset_type = ? AND deleted_at IS NULL
ORDER BY chain_id, symbol
`

func (q *Queries) ListAssetsByType(ctx context.Context, assetType string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByType, assetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ChainID,
			&i.Channel,
			&i.AssetType,
			&i.CoingeckoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalancesByAccount = `-- name: ListBalancesByAccount :many
SELECT id, created_at, updated_at, deleted_at, account_id, asset_id, amount, last_updated_height, is_delegated, is_staked, is_vesting FROM balances
WHERE account_id = ? AND deleted_at IS NULL
ORDER BY asset_id
`

func (q *Queries) ListBalancesByAccount(ctx context.Context, accountID string) ([]Balance, error) {
	rows, err := q.db.QueryContext(ctx, listBalancesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountID,
			&i.AssetID,
			&i.Amount,
			&i.LastUpdatedHeight,
			&i.IsDelegated,
			&i.IsStaked,
			&i.IsVesting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChains = `-- name: ListChains :many
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE deleted_at IS NULL
ORDER BY network_type, chain_name
`

func (q *Queries) ListChains(ctx context.Context) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, listChains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chain
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChainID,
			&i.ChainName,
			&i.PrettyName,
			&i.NetworkType,
			&i.Bech32Prefix,
			&i.DaemonName,
			&i.NodeHome,
			&i.Slip44,
			&i.Fees,
			&i.StakingDenom,
			&i.LogoUri,
			&i.Apis,
			&i.Explorers,
			&i.IsEnabled,
			&i.Status,
			&i.Codebase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChainsByNetworkType = `-- name: ListChainsByNetworkType :many
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE network_type = ? AND deleted_at IS NULL
ORDER BY chain_name
`

func (q *Queries) ListChainsByNetworkType(ctx context.Context, networkType string) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, listChainsByNetworkType, networkType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chain
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChainID,
			&i.ChainName,
			&i.PrettyName,
			&i.NetworkType,
			&i.Bech32Prefix,
			&i.DaemonName,
			&i.NodeHome,
			&i.Slip44,
			&i.Fees,
			&i.StakingDenom,
			&i.LogoUri,
			&i.Apis,
			&i.Explorers,
			&i.IsEnabled,
			&i.Status,
			&i.Codebase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChainsByStatus = `-- name: ListChainsByStatus :many
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE status = ? AND deleted_at IS NULL
ORDER BY network_type, chain_name
`

func (q *Queries) ListChainsByStatus(ctx context.Context, status string) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, listChainsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chain
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChainID,
			&i.ChainName,
			&i.PrettyName,
			&i.NetworkType,
			&i.Bech32Prefix,
			&i.DaemonName,
			&i.NodeHome,
			&i.Slip44,
			&i.Fees,
			&i.StakingDenom,
			&i.LogoUri,
			&i.Apis,
			&i.Explorers,
			&i.IsEnabled,
			&i.Status,
			&i.Codebase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChains = `-- name: ListEnabledChains :many
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE is_enabled = true AND deleted_at IS NULL
ORDER BY network_type, chain_name
`

func (q *Queries) ListEnabledChains(ctx context.Context) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledChains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chain
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChainID,
			&i.ChainName,
			&i.PrettyName,
			&i.NetworkType,
			&i.Bech32Prefix,
			&i.DaemonName,
			&i.NodeHome,
			&i.Slip44,
			&i.Fees,
			&i.StakingDenom,
			&i.LogoUri,
			&i.Apis,
			&i.Explorers,
			&i.IsEnabled,
			&i.Status,
			&i.Codebase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssetsByName = `-- name: SearchAssetsByName :many
SELECT id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id FROM assets
WHERE name LIKE ? AND deleted_at IS NULL
ORDER BY chain_id, name
LIMIT 100
`

func (q *Queries) SearchAssetsByName(ctx context.Context, name string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, searchAssetsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.ChainID,
			&i.Channel,
			&i.AssetType,
			&i.CoingeckoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChainsByName = `-- name: SearchChainsByName :many
SELECT id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase FROM chains
WHERE (chain_name LIKE ? OR pretty_name LIKE ?) AND deleted_at IS NULL
ORDER BY network_type, chain_name
LIMIT 100
`

type SearchChainsByNameParams struct {
	ChainName  string `json:"chain_name"`
	PrettyName string `json:"pretty_name"`
}

func (q *Queries) SearchChainsByName(ctx context.Context, arg SearchChainsByNameParams) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, searchChainsByName, arg.ChainName, arg.PrettyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chain
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChainID,
			&i.ChainName,
			&i.PrettyName,
			&i.NetworkType,
			&i.Bech32Prefix,
			&i.DaemonName,
			&i.NodeHome,
			&i.Slip44,
			&i.Fees,
			&i.StakingDenom,
			&i.LogoUri,
			&i.Apis,
			&i.Explorers,
			&i.IsEnabled,
			&i.Status,
			&i.Codebase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAsset = `-- name: SoftDeleteAsset :exec
UPDATE assets
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteAsset(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteAsset, id)
	return err
}

const softDeleteBalance = `-- name: SoftDeleteBalance :exec
UPDATE balances
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteBalance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteBalance, id)
	return err
}

const softDeleteChain = `-- name: SoftDeleteChain :exec
UPDATE chains
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteChain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteChain, id)
	return err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET 
    name = ?,
    decimals = ?,
    channel = ?,
    asset_type = ?,
    coingecko_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, symbol, decimals, chain_id, channel, asset_type, coingecko_id
`

type UpdateAssetParams struct {
	Name        string         `json:"name"`
	Decimals    int64          `json:"decimals"`
	Channel     string         `json:"channel"`
	AssetType   string         `json:"asset_type"`
	CoingeckoID sql.NullString `json:"coingecko_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, updateAsset,
		arg.Name,
		arg.Decimals,
		arg.Channel,
		arg.AssetType,
		arg.CoingeckoID,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.ChainID,
		&i.Channel,
		&i.AssetType,
		&i.CoingeckoID,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE balances
SET 
    amount = ?,
    last_updated_height = ?,
    is_delegated = ?,
    is_staked = ?,
    is_vesting = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, account_id, asset_id, amount, last_updated_height, is_delegated, is_staked, is_vesting
`

type UpdateBalanceParams struct {
	Amount            string `json:"amount"`
	LastUpdatedHeight int64  `json:"last_updated_height"`
	IsDelegated       bool   `json:"is_delegated"`
	IsStaked          bool   `json:"is_staked"`
	IsVesting         bool   `json:"is_vesting"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, updateBalance,
		arg.Amount,
		arg.LastUpdatedHeight,
		arg.IsDelegated,
		arg.IsStaked,
		arg.IsVesting,
		arg.ID,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.AssetID,
		&i.Amount,
		&i.LastUpdatedHeight,
		&i.IsDelegated,
		&i.IsStaked,
		&i.IsVesting,
	)
	return i, err
}

const updateChain = `-- name: UpdateChain :one
UPDATE chains
SET 
    chain_name = ?,
    pretty_name = ?,
    network_type = ?,
    bech32_prefix = ?,
    daemon_name = ?,
    node_home = ?,
    slip44 = ?,
    fees = ?,
    staking_denom = ?,
    logo_uri = ?,
    apis = ?,
    explorers = ?,
    is_enabled = ?,
    status = ?,
    codebase = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase
`

type UpdateChainParams struct {
	ChainName    string         `json:"chain_name"`
	PrettyName   string         `json:"pretty_name"`
	NetworkType  string         `json:"network_type"`
	Bech32Prefix string         `json:"bech32_prefix"`
	DaemonName   string         `json:"daemon_name"`
	NodeHome     string         `json:"node_home"`
	Slip44       int64          `json:"slip44"`
	Fees         string         `json:"fees"`
	StakingDenom string         `json:"staking_denom"`
	LogoUri      sql.NullString `json:"logo_uri"`
	Apis         string         `json:"apis"`
	Explorers    sql.NullString `json:"explorers"`
	IsEnabled    bool           `json:"is_enabled"`
	Status       string         `json:"status"`
	Codebase     sql.NullString `json:"codebase"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateChain(ctx context.Context, arg UpdateChainParams) (Chain, error) {
	row := q.db.QueryRowContext(ctx, updateChain,
		arg.ChainName,
		arg.PrettyName,
		arg.NetworkType,
		arg.Bech32Prefix,
		arg.DaemonName,
		arg.NodeHome,
		arg.Slip44,
		arg.Fees,
		arg.StakingDenom,
		arg.LogoUri,
		arg.Apis,
		arg.Explorers,
		arg.IsEnabled,
		arg.Status,
		arg.Codebase,
		arg.ID,
	)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChainID,
		&i.ChainName,
		&i.PrettyName,
		&i.NetworkType,
		&i.Bech32Prefix,
		&i.DaemonName,
		&i.NodeHome,
		&i.Slip44,
		&i.Fees,
		&i.StakingDenom,
		&i.LogoUri,
		&i.Apis,
		&i.Explorers,
		&i.IsEnabled,
		&i.Status,
		&i.Codebase,
	)
	return i, err
}

const updateChainStatus = `-- name: UpdateChainStatus :one
UPDATE chains
SET 
    is_enabled = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, chain_id, chain_name, pretty_name, network_type, bech32_prefix, daemon_name, node_home, slip44, fees, staking_denom, logo_uri, apis, explorers, is_enabled, status, codebase
`

type UpdateChainStatusParams struct {
	IsEnabled bool   `json:"is_enabled"`
	Status    string `json:"status"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateChainStatus(ctx context.Context, arg UpdateChainStatusParams) (Chain, error) {
	row := q.db.QueryRowContext(ctx, updateChainStatus, arg.IsEnabled, arg.Status, arg.ID)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChainID,
		&i.ChainName,
		&i.PrettyName,
		&i.NetworkType,
		&i.Bech32Prefix,
		&i.DaemonName,
		&i.NodeHome,
		&i.Slip44,
		&i.Fees,
		&i.StakingDenom,
		&i.LogoUri,
		&i.Apis,
		&i.Explorers,
		&i.IsEnabled,
		&i.Status,
		&i.Codebase,
	)
	return i, err
}
