# yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: '3'
tasks:
  build:
    preconditions:
      - sh: command -v pnpm
    sources:
      - '**/*.ts'
      - '**/*.js'
    generates:
      - dist
      - cdn
    deps:
      - task: install:shoelace
    cmds:
      - gum spin --spinner dot --title "Minifying Icon Set..." -- pnpm run minify
      - gum log --level info --time kitchen "[SHOELACE] Compressed Icon Set"
      - gum spin --spinner dot --title "Building Web Components..." -- pnpm run build
      - gum log --level info --time kitchen "[SHOELACE] Web Components built"
  install:
    preconditions:
      - sh: command -v pnpm
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml
      - node_modules
    cmds:
      - pnpm install
  publish:
    preconditions:
      - sh: command -v npm
    cmds:
      - npm publish
