VERSION 0.8
FROM tinygo/tinygo:0.37.0
WORKDIR /work

build:
    COPY . .
    RUN tinygo build -o signer.wasm -target wasip1 -buildmode=c-shared .
    SAVE ARTIFACT signer.wasm AS LOCAL ./dist/signer.wasm

