# yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
tasks:
  default:
    cmds:
      - task: gen:templ

  build:
    preconditions:
      - sh: command -v pnpm
    sources:
      - "**/*.ts"
      - "**/*.js"
    generates:
      - dist
    deps:
      - task: install:cosmes
    cmds:
      - gum spin --spinner dot --title "Generating Chain Registry..." -- pnpm run gen:registry
      - gum log --level info --time kitchen "[COSMES] Chain Registry generated"
      - gum spin --spinner dot --title "Generating Go from Templ..." -- pnpm run gen:protobufs
      - gum log --level info --time kitchen "[COSMES] Protobufs generated"
      - gum spin --spinner dot --title "Generating Go from Templ..." -- pnpm run build
      - gum log --level info --time kitchen "[COSMES] Packages built"

  install:
    preconditions:
      - sh: command -v pnpm
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml
      - node_modules
    cmds:
      - pnpm install

  publish:
    preconditions:
      - sh: command -v npm
    cmds:
      - npm publish
