// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file babylon/btccheckpoint/v1/tx.proto (package babylon.btccheckpoint.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgInsertBTCSpvProof, MsgInsertBTCSpvProofResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "babylon.btccheckpoint.v1.Msg";

/**
 * InsertBTCSpvProof tries to insert a new checkpoint into the store.
 *
 * @generated from rpc babylon.btccheckpoint.v1.Msg.InsertBTCSpvProof
 */
export const MsgInsertBTCSpvProofService = {
  typeName: TYPE_NAME,
  method: "InsertBTCSpvProof",
  Request: MsgInsertBTCSpvProof,
  Response: MsgInsertBTCSpvProofResponse,
} as const;

/**
 * UpdateParams updates the btccheckpoint module parameters.
 *
 * @generated from rpc babylon.btccheckpoint.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

